import { useEffect, useRef, useState } from "react";
import { useStore } from "../store";
import type { OmpConfigEntry, OmpConfigSection, OmpConfigSectionId } from "../lib/types";
import { Refresh, Search } from "./icons";

/**
 * Schema-driven editor for omp's config.yml (the keys curated in
 * src/main/omp-config.ts). Values come from `omp config list --json`; every
 * write goes through `omp config set/reset`, which validates and coerces, so
 * the UI can never corrupt the YAML.
 */

const SECTION_LABEL: Record<OmpConfigSectionId, [string, string]> = {
  appearance: ["外观", "Appearance"],
  context: ["上下文", "Context"],
  files: ["文件与工具", "Files & Tools"],
  interaction: ["交互", "Interaction"],
  model: ["模型", "Model"],
  memory: ["记忆", "Memory"],
  providers: ["提供商", "Providers"],
  advanced: ["高级", "Advanced"],
};

/**
 * Chinese descriptions for the curated keys (fallback: omp's English
 * description from `omp config list --json`). Kept here so the panel
 * localizes without touching the main-process IPC contract.
 */
const ZH_DESC: Record<string, string> = {
  // appearance
  symbolPreset: "图标与符号使用的字形集（Unicode、Nerd Font 或 ASCII）",
  colorBlindMode: "使用蓝色代替绿色显示 diff 新增内容",
  "theme.dark": "终端为深色背景时使用的主题",
  "theme.light": "终端为浅色背景时使用的主题",
  showHardwareCursor: "显示终端光标以支持输入法（IME）",
  "terminal.showImages": "在终端中内联渲染图片",
  "terminal.showProgress": "在 agent 运行或上下文维护时发送 OSC 9;4 不确定进度",
  "images.autoResize": "将大图缩放到最大 2000x2000 以提升模型兼容性",
  "images.blockImages": "阻止向 LLM 提供商发送图片",
  "display.shimmer": "加载/工作消息的动画样式",
  "display.smoothStreaming": "流式输出到达时平滑显示助手文本与工具输入",
  "display.hideToolActivity": "从对话记录中隐藏模型发起的工具调用与结果",
  "display.showTokenUsage": "在助手消息上显示每轮 token 用量",
  "display.cacheMissMarker": "在提示缓存未命中的助手轮次上方显示分隔线",
  "display.collapseCompacted": "在实时对话中把压缩前的历史折叠到摘要分隔线之下；关闭则保留完整对话，在每个压缩点显示分隔线",
  "tui.textSizing": "使用 Kitty 的 OSC 66 协议把 Markdown H1 标题放大 2 倍。仅对 Kitty 终端生效；默认关闭",
  "tui.renderMermaid": "把 Mermaid 围栏代码块渲染为 ASCII 图",
  "tui.hyperlinks": "把路径和 URL 包装成 OSC 8 超链接，支持终端内点击打开（auto：自动检测支持；off：从不；always：始终）",
  "tui.tight": "去掉终端输出左右各 1 个字符的水平留白",
  "tui.titleState": "在终端标题分隔符中显示 agent 运行状态：工作时为旋转动画（Windows 为静态冒号）、轮到您时显示 '>'、agent 等待您时显示 '!'",
  "tui.imeSafeCursor": "把提示符下边框移到单独一行，避免 macOS 输入法候选框将其顶开",
  "statusLine.preset": "预置的状态栏配置",
  "statusLine.separator": "状态栏各段之间的分隔样式",
  "statusLine.sessionAccent": "使用会话名颜色作为编辑器边框与状态栏间隙的颜色",
  "statusLine.transparent": "状态栏使用终端默认背景而非主题的 statusLineBg。Powerline 端帽会被去掉，因为它们需要对比色填充才能与周围终端衔接",
  "statusLine.compactThinkingLevel": "把思考档位显示为模型名上的单个图标，而不是额外的 ' · <档位>' 后缀",
  "statusLine.showHookStatus": "在状态栏下方显示 hook 状态消息",
  // context
  "contextPromotion.enabled": "上下文溢出时切换到更大上下文的模型，而不是压缩上下文",
  "workspace.additionalDirectories": "额外的工作区目录，作为附加根目录加入每个会话（多根工作区）。可通过 /add-dir 和 /remove-dir 实时管理。路径相对于 cwd 解析；建议使用绝对路径",
  "compaction.enabled": "上下文过大时自动压缩",
  "compaction.midTurnEnabled": "在安全的中途工具循环边界检查压缩阈值（在下次提供商请求之前）",
  "compaction.strategy": "选择就地上下文维护、自动交接、外科式清理（删除重内容）、snapcompact（把历史归档为高密度图片）或关闭自动维护（off）",
  "compaction.thresholdPercent": "上下文维护的百分比阈值；设为 Default 使用旧的基于预留空间的行为",
  "compaction.thresholdTokens": "上下文维护的固定 token 上限；设置后覆盖百分比",
  "compaction.autoContinue": "压缩完成后是否自动继续任务",
  "compaction.keepRecentTokens": "压缩时保留的最近 token 数",
  "snapcompact.systemPrompt": "实验性：把选定的系统提示文本渲染为高密度 PNG 图片并附加到第一条用户消息（仅限视觉模型）。节省 token，但图片化文本会失去提示缓存",
  "snapcompact.toolResults": "实验性：把大型历史工具结果渲染为高密度 PNG 图片而非文本（仅限视觉模型）。节省累积的读取/搜索输出 token",
  "snapcompact.shape": "snapcompact 打印文本所用的边框形状（压缩归档与内联成像）。自动选择适配当前模型的形状",
  "branchSummary.enabled": "离开分支时提示生成摘要",
  "ttsr.enabled": "输出匹配规则模式时中途打断 agent（时光倒流流式规则 TTSR）",
  "ttsr.contextMode": "TTSR 触发时如何处理部分输出",
  "ttsr.interruptMode": "何时中断流式输出，而不是在完成后注入警告",
  "ttsr.repeatMode": "规则可以重复触发的方式：每会话一次或消息间隔后",
  "ttsr.repeatGap": "规则可再次触发前需要间隔的消息数",
  "ttsr.builtinRules": "加载随 agent 附带的默认规则（可用 ttsr.disabledRules 逐条覆盖）",
  // files
  "edit.mode": "选择编辑工具变体（replace、patch、hashline 或 apply_patch）",
  "edit.fuzzyMatch": "接受空白差异的高置信度模糊匹配",
  "edit.fuzzyThreshold": "接受模糊匹配的相似度阈值（0-1）",
  "edit.streamingAbort": "补丁预览失败时中止流式编辑工具调用",
  "edit.blockAutoGenerated": "禁止编辑看似自动生成的文件（protoc、sqlc、swagger 等）",
  "edit.enforceSeenLines": "拒绝编辑锚定在先前读取/搜索未完整显示过的行",
  readLineNumbers: "read 工具输出默认带行号",
  "read.defaultLimit": "agent 调用 read 未指定行数时默认返回的行数",
  "read.renderMarkdown": "把 Markdown 读取结果渲染为格式化的终端 Markdown 预览而非原始源码",
  "read.toolResultPreview": "在对话记录中内联渲染 read 工具结果，而非摘要行",
  "read.summarize.enabled": "read 未指定选择器时返回结构化代码摘要",
  "read.summarize.prose": "对 Markdown 与纯文本读取返回结构化摘要",
  "read.summarize.minBodyLines": "多行正文/字面量达到该长度后 read 摘要才折叠它",
  "read.summarize.minCommentLines": "多行块注释达到该长度后 read 摘要才折叠它",
  "read.summarize.minTotalLines": "总行数更少的文件直接原样读取，不做结构化摘要",
  "lsp.enabled": "启用 lsp 工具实现代码智能（定义、引用、诊断、重命名）",
  "lsp.lazy": "在首次使用时才启动语言服务器（lsp 工具或编辑匹配的文件类型），而非会话启动时",
  "lsp.shared": "通过守护 broker 在多个 omp 实例间共享每个项目的语言服务器（不可用时回退到私有服务器）",
  "lsp.formatOnWrite": "写入后自动用 LSP 格式化代码文件",
  "lsp.diagnosticsOnWrite": "写入代码文件后返回 LSP 诊断",
  "lsp.diagnosticsOnEdit": "编辑代码文件后返回 LSP 诊断",
  "lsp.diagnosticsDeduplicate": "抑制已为该文件展示过的编辑后 LSP 诊断；只呈现新增或变化的",
  "tools.format": "控制工具如何暴露给模型。Auto 使用提供商原生工具调用（除非所选模型标记为不支持），否则回退到 GLM 专有方言；Native 强制使用提供商原生工具，其余值强制使用指定专有方言。会话启动时生效",
  // interaction
  autoResume: "自动恢复当前目录下最近的会话",
  "power.sleepPrevention": "活动会话期间阻止 macOS 睡眠。每个级别是累积的——包含所有更低级别的标志",
  "git.enabled": "在 TUI 中显示 git 分支、状态与 PR 信息，并监听仓库元数据",
  steeringMode: "agent 工作时如何处理排队中的消息",
  followUpMode: "一轮结束后如何排空后续消息",
  interruptMode: "steering 消息何时打断工具执行",
  "loop.mode": "每次 /loop 迭代之间、重新提交提示词之前发生什么",
  doubleEscapeAction: "编辑器为空时连按两次 Escape 的动作",
  treeFilterMode: "打开会话树时的默认过滤模式",
  autocompleteMaxVisible: "自动补全下拉列表的最大可见项数（3-20）",
  emojiAutocomplete: "从 `:name:` 短代码建议 emoji，并展开 `:D`、`:-)` 等文本表情",
  "paste.largeMenuThreshold": "粘贴内容达到该行数时，提供菜单选择：包成代码块、包成 XML 标签或保存到文件。0 禁用该菜单（大粘贴仍折叠为 [Paste] 标记）",
  "startup.quiet": "跳过欢迎界面与启动状态消息",
  "startup.showSplash": "正常交互式启动时显示完整的动画设置启动画面（不重跑设置）。静默启动仍会抑制它",
  "startup.setupWizard": "每个设置版本首次展示新增的引导步骤",
  "startup.checkUpdate": "启动时检查 omp 更新",
  "startup.changelogMode": "选择更新说明初始显示为摘要、完整详情还是保持隐藏",
  "marketplace.autoUpdate": "启动时检查插件更新",
  "magicKeywords.enabled": "启用对独立 ultrathink、orchestrate 与 workflowz 关键字的隐藏提示",
  "magicKeywords.ultrathink": "允许独立的 ultrathink 请求最大自动思考并附加其隐藏提示",
  "magicKeywords.orchestrate": "允许独立的 orchestrate 附加其隐藏的多 agent 编排提示",
  "magicKeywords.workflow": "允许独立的 workflowz 附加其隐藏的评测工作流提示",
  "completion.notify": "agent 完成一轮时通知",
  "error.notify": "agent 出错停止时通知",
  "ask.timeout": "超过该秒数后自动选择推荐的 ask 选项（0 禁用）",
  "ask.notify": "ask 工具等待输入时通知",
  "recap.enabled": "终端空闲一段时间后生成简短 LLM 回顾，说明当前进展",
  "recap.idleSeconds": "显示回顾前需要空闲等待的秒数",
  "collab.displayName": "协作参与者看到的名称（默认：操作系统用户名）",
  "share.serverUrl": "/share 使用的分享查看/上传地址（加密 blob 上传 + 查看器；链接格式为 <base>/<id>#<key>）",
  "share.store": "/share 上传加密会话 blob 的位置",
  "share.redactSecrets": "上传前对 /share 快照运行密钥混淆器（使用 secrets.* 配置）",
  "tools.approvalMode": "工具调用的默认审批行为。'Always ask' 只自动批准只读工具；'Write' 自动批准读取与工作区写入工具；'Yolo' 自动批准所有层级，但用户策略仍可能提示或阻止",
  "features.unexpectedStopDetection": "用小模型检测「assistant 说会继续但未调用工具就停止」的情况，并自动提示它继续",
  // model
  personality: "渲染进系统提示词个性块中的沟通风格",
  textVerbosity: "OpenAI Responses 与 Codex 的回复详细度（low、medium 或 high）",
  temperature: "采样温度（0 = 确定性，1 = 有创造力，-1 = 提供商默认）",
  topP: "核采样截断（0-1，-1 = 提供商默认）",
  topK: "从 Top-K token 中采样（-1 = 提供商默认）",
  minP: "最小概率阈值（0-1，-1 = 提供商默认）",
  presencePenalty: "对已出现 token 的惩罚（-1 = 提供商默认）",
  repetitionPenalty: "对重复 token 的惩罚（-1 = 提供商默认）",
  includeModelInPrompt: "在系统提示词中暴露当前模型标识，让 agent 知道自己是哪个模型",
  includeWorkspaceTree: "在系统提示词中渲染工作区目录树。警告：文件修改时可能破坏跨会话的提示缓存",
  proseOnlyThinking: "从思考摘要中省略代码块，用省略号代替",
  omitThinking: "指示上游提供商完全省略响应中的思考摘要（在支持的提供商上）",
  inlineToolDescriptors: "在系统提示词中渲染完整工具描述，并从提供商工具 schema 中剥离顶层/嵌套描述，使描述文本只发送一次。Auto 对 Gemini 模型启用，其余禁用",
  "images.describeForTextModels": "当图片附加到不支持视觉的模型时，保存到 local:// 下并用视觉模型注入描述，而不是丢弃它",
  modelRoleStorage: "模型选择器角色分配保存的位置",
  "advisor.enabled": "配对第二个模型（分配 'advisor' 角色）被动审查每一轮并注入笔记",
  "advisor.syncBacklog": "advisor 落后该轮数时暂停主 agent 最多 30 秒。Off 关闭追赶延迟",
  "prewalk.enabled": "在活动模型上开始，计划提示的待办列表出现后、首次编辑/写入时切换到快速/廉价模型（默认 'smol' 角色）——强模型规划、提交待办并开始实现后再交接。可用 --prewalk / --no-prewalk 按会话覆盖",
  "retry.maxRetries": "API 错误时的最大重试次数",
  "retry.maxDelayMs": "重试之间的最大等待毫秒数。当提供商要求等待超过此值且凭证/模型回退都失败时，请求快速失败而不是长时间休眠（如 Anthropic 3 小时限速窗口）",
  "retry.modelFallback": "允许重试恢复切换到配置的回退模型",
  "retry.usageAwareFallback": "在硬性用量上限前，使用可靠的编码计划配额报告优先选择同提供商账号，然后使用配置的回退模型。普通配置的 API key 不参与",
  "thinkingBudgets.minimal": "「minimal」档的思考预算（token 数）",
  "thinkingBudgets.low": "「low」档的思考预算（token 数）",
  "thinkingBudgets.medium": "「medium」档的思考预算（token 数）",
  "thinkingBudgets.high": "「high」档的思考预算（token 数）",
  "thinkingBudgets.xhigh": "「xhigh」档的思考预算（token 数）",
  "thinkingBudgets.max": "「max」档的思考预算（token 数）",
  "model.loopGuard.enabled": "为模型推理与正文启用自动流循环检测",
  // memory
  "memory.backend": "Off、本地摘要流水线、Mnemopi SQLite 或 Hindsight 远程记忆",
  "autolearn.enabled": "agent 停止后，提示它把经验存入记忆并创建/增强隔离的受管技能",
  "autolearn.autoContinue": "开启时，停止后自动运行一次私有的捕获轮次（消耗额外 token）。关闭时只保留常驻的自动学习指引",
  "mnemopi.scoping": "global = 一个共享记忆库；per-project = 每个 cwd 独立记忆库；per-project-tagged = 项目本地写入 + 全局召回可见",
  "mnemopi.autoRecall": "把本地记忆召回进每个会话的第一轮",
  "mnemopi.autoRetain": "把已完成的对话轮次存入本地 Mnemopi 记忆",
  "mnemopi.llmMode": "不使用 LLM、使用在线微型模型（/models 中的 TINY 角色，否则 @smol）、或使用远程 OpenAI 兼容端点",
  "mnemopi.debug": "启用 Mnemopi 调试日志",
  "hindsight.apiUrl": "Hindsight 服务器地址（Cloud 或自托管）",
  "hindsight.scoping": "global = 一个共享记忆库；per-project = 每个 cwd 独立记忆库；per-project-tagged = 带项目标签的共享记忆库，召回时全局与项目记忆合并",
  "hindsight.autoRecall": "在每个会话第一轮召回记忆",
  "hindsight.autoRetain": "每 N 轮及会话边界保存对话记录",
  "hindsight.retainMode": "full-session = 每个会话 upsert 一份文档，last-turn = 分块",
  "hindsight.mentalModelsEnabled": "启动时把精选的 reflect 摘要（思维模型）读入开发者指引。只加载库中已有模型，不写入。配合 hindsight.mentalModelAutoSeed 可自动创建内置种子集",
  // providers
  disabledProviders: "禁用的提供商列表（其模型不会出现在选择器中）",
  "web_search.enabled": "启用 web_search 工具获取实时网页结果。Console Go 等 Responses 接口会把 web_search 当保留名，冲突时可先关掉",
  "providers.webSearchOrder": "web_search 工具的优先提供商列表；未列出的提供商保持默认顺序",
  "providers.webSearchExclude": "web_search 绝不使用的提供商，即使作为回退",
  "providers.webSearchTimeoutSeconds": "每个提供商搜索传输的硬超时秒数，超时后 web_search 进入下一个回退（最大 300）",
  "providers.imageOrder": "图片生成的优先提供商列表；未列出的提供商跟随当前会话提供商与内置顺序",
  "providers.autoThinkingModel": "「auto」思考档位的难度分类器：默认在线（/models 中的 TINY 角色，否则 smol），或本地设备端模型",
  "providers.autoThinkingMaxEffort": "「auto」分类器可解析的最高档位。xhigh 使分类器保持在最高档之下，只有显式 ultrathink 才能到达 max；max 允许分类器判定的非凡轮次在支持它的模型上计费顶级档位",
  "providers.tinyModel": "会话标题模型：默认在线（/models 中的 TINY 角色，否则 @smol），或本地设备端模型",
  "providers.tinyModelDevice": "本地微型模型（标题 + 记忆）的 ONNX 执行提供程序。默认仅 CPU 推理。PI_TINY_DEVICE 环境变量可覆盖",
  "providers.tinyModelDtype": "本地微型模型的 ONNX 量化/精度。默认使用每个模型自带的 dtype（q4）；精度越低越快，越高越忠实。PI_TINY_DTYPE 环境变量可覆盖",
  "providers.tts": "tts 工具的后端：本地设备端神经 TTS（Kokoro-82M）或 xAI Grok Voice",
  "tts.localVoice": "本地 TTS 后端使用的 Kokoro 音色（美式/英式，女声/男声）",
  "speech.enabled": "流式输出助手回复时通过扬声器朗读",
  "speech.mode": "朗读内容：all = 助手消息 + 思考；assistant = 仅消息；yield = 仅轮次结束时的最终消息",
  "speech.voice": "朗读助手输出时使用的 Kokoro 音色",
  "live.voice": "Codex 驱动的实时语音会话使用的音色",
  // advanced
  shellPath: "Shell 可执行文件路径（默认使用系统 shell）",
  "browser.headless": "以无头模式启动浏览器（关闭可显示浏览器界面）",
  "statusLine.leftSegments": "状态栏左侧的段配置",
  "statusLine.rightSegments": "状态栏右侧的段配置",
  modelProviderOrder: "模型选择器中提供商的排列顺序",
  cycleOrder: "模型循环切换的顺序",
};

function Toggle({ checked, onChange }: { checked: boolean; onChange: (v: boolean) => void }) {
  return (
    <button type="button" className={`set-toggle ${checked ? "on" : ""}`} aria-checked={checked} role="switch" onClick={() => onChange(!checked)}>
      <span className="set-toggle-knob" />
    </button>
  );
}

function textFor(entry: OmpConfigEntry): string {
  const v = entry.value;
  if (v === undefined || v === null) return "";
  if (entry.type === "array" || entry.type === "record") return JSON.stringify(v, null, 2);
  return String(v);
}

interface RowProps {
  entry: OmpConfigEntry;
  language: "en" | "zh";
  saving: boolean;
  onCommit: (entry: OmpConfigEntry, value: unknown) => Promise<void>;
  onReset: (entry: OmpConfigEntry) => Promise<void>;
}

function Row({ entry, language, saving, onCommit, onReset }: RowProps) {
  const [text, setText] = useState(() => textFor(entry));
  const [jsonOk, setJsonOk] = useState(true);
  const inputRef = useRef<HTMLInputElement | null>(null);
  const areaRef = useRef<HTMLTextAreaElement | null>(null);
  const desc = language === "zh" ? (ZH_DESC[entry.key] ?? entry.description) : entry.description;
  // Latest text for blur commits: state updates flush after the input event,
  // so a blur arriving in the same tick would read a stale closure.
  const textRef = useRef(text);
  const setDraft = (t: string) => {
    setText(t);
    textRef.current = t;
  };

  // Reflect committed values (e.g. another row's save or a reset) without
  // clobbering the text while the user is actively typing in this row.
  useEffect(() => {
    if (document.activeElement === inputRef.current || document.activeElement === areaRef.current) return;
    setDraft(textFor(entry));
  }, [entry.value]);

  const commitText = () => {
    const current = textRef.current;
    if (entry.type === "number") {
      const t = current.trim();
      if (t === "") return void onReset(entry);
      const n = Number(t);
      if (Number.isNaN(n)) return;
      return void onCommit(entry, n);
    }
    if (entry.type === "array" || entry.type === "record") {
      const t = current.trim();
      if (t === "") return void onReset(entry);
      try {
        return void onCommit(entry, JSON.parse(t));
      } catch {
        setJsonOk(false);
        return;
      }
    }
    if (current.trim() === "") return void onReset(entry);
    return void onCommit(entry, current);
  };

  let control: React.ReactNode;
  if (entry.type === "boolean") {
    control = <Toggle checked={Boolean(entry.value)} onChange={(v) => void onCommit(entry, v)} />;
  } else if (entry.type === "enum" && entry.options?.length) {
    control = (
      <select
        className="set-select"
        value={String(entry.value ?? "")}
        onChange={(e) => void onCommit(entry, e.target.value)}
      >
        {entry.value === undefined && <option value="">{language === "zh" ? "（未设置）" : "(unset)"}</option>}
        {entry.options.map((o) => (
          <option key={o} value={o}>
            {o}
          </option>
        ))}
      </select>
    );
  } else if (entry.type === "number") {
    control = (
      <input
        ref={inputRef}
        className="set-input"
        type="number"
        value={text}
        placeholder={language === "zh" ? "（未设置）" : "(unset)"}
        onChange={(e) => setDraft(e.target.value)}
        onBlur={commitText}
        onKeyDown={(e) => {
          if (e.key === "Enter") (e.target as HTMLInputElement).blur();
        }}
      />
    );
  } else if (entry.type === "array" || entry.type === "record") {
    control = (
      <div className="set-json-wrap">
        <textarea
          ref={areaRef}
          className={`set-json ${jsonOk ? "" : "err"}`}
          spellCheck={false}
          value={text}
          placeholder={entry.type === "array" ? '["a", "b"]' : '{"key": "value"}'}
          onChange={(e) => {
            setDraft(e.target.value);
            setJsonOk(true);
          }}
          onBlur={commitText}
        />
        {!jsonOk && <div className="set-json-err">JSON 语法错误</div>}
      </div>
    );
  } else {
    // string, or enum without parseable options
    control = (
      <input
        ref={inputRef}
        className="set-input"
        type="text"
        value={text}
        placeholder={language === "zh" ? "（未设置）" : "(unset)"}
        onChange={(e) => setDraft(e.target.value)}
        onBlur={commitText}
        onKeyDown={(e) => {
          if (e.key === "Enter") (e.target as HTMLInputElement).blur();
        }}
      />
    );
  }

  return (
    <div className="set-row">
      <label className="set-label set-omp-label" title={entry.key}>
        {entry.key}
      </label>
      <div className="set-control">
        <div className="set-omp-ctrl">
          {control}
          <button
            type="button"
            className="set-omp-reset"
            title={language === "zh" ? "恢复默认" : "Reset to default"}
            onClick={() => void onReset(entry)}
          >
            {saving ? <span className="spinner" /> : <Refresh size={12} />}
          </button>
        </div>
        {desc && <div className="set-hint">{desc}</div>}
      </div>
    </div>
  );
}

export function OmpConfigPanel() {
  const language = useStore((s) => s.config?.language || "en");
  const pushToast = useStore((s) => s.pushToast);
  const [sections, setSections] = useState<OmpConfigSection[] | null>(null);
  const [query, setQuery] = useState("");
  const [savingKey, setSavingKey] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const reload = async () => {
    try {
      setError(null);
      const s = await window.pi.settings.getOmpConfig();
      setSections(s as OmpConfigSection[]);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : String(err));
    }
  };

  useEffect(() => {
    void reload();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const run = async (fn: () => Promise<void>) => {
    try {
      await fn();
    } catch (err: unknown) {
      pushToast("error", (err instanceof Error ? err.message : String(err)).replace(/^Error:\s*/, ""));
    }
  };

  const commit = async (entry: OmpConfigEntry, value: unknown) => {
    setSavingKey(entry.key);
    await run(() => window.pi.settings.setOmpConfigKey(entry.key, value, entry.type));
    setSavingKey(null);
    void reload();
    void useStore.getState().refreshShowTokenUsage();
  };

  const reset = async (entry: OmpConfigEntry) => {
    setSavingKey(entry.key);
    await run(() => window.pi.settings.resetOmpConfigKey(entry.key));
    setSavingKey(null);
    void reload();
    void useStore.getState().refreshShowTokenUsage();
  };

  const q = query.trim().toLowerCase();
  const filtered = (sections || [])
    .map((sec) => ({
      ...sec,
      entries: q
        ? sec.entries.filter((e) => {
            const d = language === "zh" ? (ZH_DESC[e.key] ?? e.description) : e.description;
            return e.key.toLowerCase().includes(q) || d.toLowerCase().includes(q);
          })
        : sec.entries,
    }))
    .filter((sec) => sec.entries.length > 0);

  return (
    <div className="set-card">
      <div className="set-card-title">omp 配置（config.yml）</div>
      <div className="set-omp-toolbar">
        <span className="set-omp-search">
          <Search size={13} />
          <input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder={language === "zh" ? "搜索配置项…" : "Search settings…"}
          />
        </span>
        <button className="set-btn ghost" onClick={() => void reload()} title="重新读取 config.yml">
          <Refresh size={14} /> {language === "zh" ? "重新加载" : "Reload"}
        </button>
      </div>
      <div className="set-hint">
        {language === "zh"
          ? "写入 ~/.omp/agent/config.yml。改动对新会话立即生效；部分选项需重启会话。标红的值已由 omp 校验。"
          : "Writes ~/.omp/agent/config.yml. Changes apply to new sessions; some options need a restart. Values are validated by omp."}
      </div>
      {error && <div className="set-json-err">加载失败：{error}</div>}
      {!sections && !error && (
        <div className="set-hint">
          <span className="spinner" /> {language === "zh" ? "加载中…" : "Loading…"}
        </div>
      )}
      {filtered.map((sec) => {
        const [zh, en] = SECTION_LABEL[sec.id];
        return (
          <div key={sec.id} className="set-omp-group">
            <div className="set-omp-group-title">
              {language === "zh" ? zh : en}
              <span className="set-omp-count">{sec.entries.length}</span>
            </div>
            {sec.entries.map((e) => (
              <Row key={e.key} entry={e} language={language} saving={savingKey === e.key} onCommit={commit} onReset={reset} />
            ))}
          </div>
        );
      })}
      {filtered.length === 0 && sections && (
        <div className="set-hint">{language === "zh" ? "没有匹配的配置项。" : "No matching settings."}</div>
      )}
    </div>
  );
}
