import { execFile } from "node:child_process";
import { resolvePiRuntime } from "./pi-bridge";

/**
 * Read/write omp's own config.yml through the `omp config` CLI.
 *
 * Why the CLI instead of parsing YAML ourselves: `omp config set` performs
 * type coercion and validation (bad enums are rejected with the valid list),
 * writes nested keys correctly, and survives schema changes between omp
 * versions. The schema itself is machine-readable via `omp config list --json`,
 * so this panel is schema-driven: it renders whatever keys the allowlist below
 * selects, in whatever type omp reports.
 */

export interface OmpConfigEntry {
  key: string;
  type: string;
  /** Resolved value from `omp config list --json`; absent when unset. */
  value?: unknown;
  description: string;
  /** Enum choices, parsed from the human `omp config list` output. */
  options?: string[];
}

export type OmpConfigSectionId = "appearance" | "context" | "files" | "interaction" | "model" | "memory" | "providers" | "advanced";

export interface OmpConfigSection {
  id: OmpConfigSectionId;
  entries: OmpConfigEntry[];
}

/**
 * Curated allowlist of user-facing keys, grouped for display. Everything a
 * user would plausibly configure appears here; credentials (…token/apiKey/
 * password), internal plumbing (auth.broker, gc, memories rollout tuning,
 * shellMinimizer, bashInterceptor, searxng) and keys already covered by
 * dedicated tabs (modelRoles, defaultThinkingLevel, hideThinkingBlock) are
 * intentionally excluded. Keys unknown to the installed omp are skipped.
 */
const CONFIG_GROUPS: { id: OmpConfigSectionId; keys: string[] }[] = [
  {
    id: "appearance",
    keys: [
      "symbolPreset",
      "colorBlindMode",
      "theme.dark",
      "theme.light",
      "showHardwareCursor",
      "terminal.showImages",
      "terminal.showProgress",
      "images.autoResize",
      "images.blockImages",
      "display.shimmer",
      "display.smoothStreaming",
      "display.hideToolActivity",
      "display.showTokenUsage",
      "display.cacheMissMarker",
      "display.collapseCompacted",
      "tui.textSizing",
      "tui.renderMermaid",
      "tui.hyperlinks",
      "tui.tight",
      "tui.titleState",
      "tui.imeSafeCursor",
      "statusLine.preset",
      "statusLine.separator",
      "statusLine.sessionAccent",
      "statusLine.transparent",
      "statusLine.compactThinkingLevel",
      "statusLine.showHookStatus",
    ],
  },
  {
    id: "context",
    keys: [
      "contextPromotion.enabled",
      "workspace.additionalDirectories",
      "compaction.enabled",
      "compaction.midTurnEnabled",
      "compaction.strategy",
      "compaction.thresholdPercent",
      "compaction.thresholdTokens",
      "compaction.autoContinue",
      "compaction.keepRecentTokens",
      "snapcompact.systemPrompt",
      "snapcompact.toolResults",
      "snapcompact.shape",
      "branchSummary.enabled",
      "ttsr.enabled",
      "ttsr.contextMode",
      "ttsr.interruptMode",
      "ttsr.repeatMode",
      "ttsr.repeatGap",
      "ttsr.builtinRules",
    ],
  },
  {
    id: "files",
    keys: [
      "edit.mode",
      "edit.fuzzyMatch",
      "edit.fuzzyThreshold",
      "edit.streamingAbort",
      "edit.blockAutoGenerated",
      "edit.enforceSeenLines",
      "readLineNumbers",
      "read.defaultLimit",
      "read.renderMarkdown",
      "read.toolResultPreview",
      "read.summarize.enabled",
      "read.summarize.prose",
      "read.summarize.minBodyLines",
      "read.summarize.minCommentLines",
      "read.summarize.minTotalLines",
      "lsp.enabled",
      "lsp.lazy",
      "lsp.shared",
      "lsp.formatOnWrite",
      "lsp.diagnosticsOnWrite",
      "lsp.diagnosticsOnEdit",
      "lsp.diagnosticsDeduplicate",
      "tools.format",
    ],
  },
  {
    id: "interaction",
    keys: [
      "autoResume",
      "power.sleepPrevention",
      "git.enabled",
      "steeringMode",
      "followUpMode",
      "interruptMode",
      "loop.mode",
      "doubleEscapeAction",
      "treeFilterMode",
      "autocompleteMaxVisible",
      "emojiAutocomplete",
      "paste.largeMenuThreshold",
      "startup.quiet",
      "startup.showSplash",
      "startup.setupWizard",
      "startup.checkUpdate",
      "startup.changelogMode",
      "marketplace.autoUpdate",
      "magicKeywords.enabled",
      "magicKeywords.ultrathink",
      "magicKeywords.orchestrate",
      "magicKeywords.workflow",
      "completion.notify",
      "error.notify",
      "ask.timeout",
      "ask.notify",
      "recap.enabled",
      "recap.idleSeconds",
      "collab.displayName",
      "share.serverUrl",
      "share.store",
      "share.redactSecrets",
      "tools.approvalMode",
      "features.unexpectedStopDetection",
    ],
  },
  {
    id: "model",
    keys: [
      "personality",
      "textVerbosity",
      "temperature",
      "topP",
      "topK",
      "minP",
      "presencePenalty",
      "repetitionPenalty",
      "includeModelInPrompt",
      "includeWorkspaceTree",
      "proseOnlyThinking",
      "omitThinking",
      "inlineToolDescriptors",
      "images.describeForTextModels",
      "modelRoleStorage",
      "advisor.enabled",
      "advisor.syncBacklog",
      "prewalk.enabled",
      "retry.maxRetries",
      "retry.maxDelayMs",
      "retry.modelFallback",
      "retry.usageAwareFallback",
      "thinkingBudgets.minimal",
      "thinkingBudgets.low",
      "thinkingBudgets.medium",
      "thinkingBudgets.high",
      "thinkingBudgets.xhigh",
      "thinkingBudgets.max",
      "model.loopGuard.enabled",
    ],
  },
  {
    id: "memory",
    keys: [
      "memory.backend",
      "autolearn.enabled",
      "autolearn.autoContinue",
      "mnemopi.scoping",
      "mnemopi.autoRecall",
      "mnemopi.autoRetain",
      "mnemopi.llmMode",
      "mnemopi.debug",
      "hindsight.apiUrl",
      "hindsight.scoping",
      "hindsight.autoRecall",
      "hindsight.autoRetain",
      "hindsight.retainMode",
      "hindsight.mentalModelsEnabled",
    ],
  },
  {
    id: "providers",
    keys: [
      "disabledProviders",
      "web_search.enabled",
      "providers.webSearchOrder",
      "providers.webSearchExclude",
      "providers.webSearchTimeoutSeconds",
      "providers.imageOrder",
      "providers.autoThinkingModel",
      "providers.autoThinkingMaxEffort",
      "providers.tinyModel",
      "providers.tinyModelDevice",
      "providers.tinyModelDtype",
      "providers.tts",
      "tts.localVoice",
      "speech.enabled",
      "speech.mode",
      "speech.voice",
      "live.voice",
    ],
  },
  {
    id: "advanced",
    keys: [
      "shellPath",
      "browser.headless",
      "statusLine.leftSegments",
      "statusLine.rightSegments",
      "modelProviderOrder",
      "cycleOrder",
    ],
  },
];

interface SchemaEntry {
  type: string;
  value?: unknown;
  description?: string;
}

function runConfig(args: string[]): Promise<{ stdout: string; stderr: string }> {
  return resolvePiRuntime().then(
    (rt) =>
      new Promise<{ stdout: string; stderr: string }>((resolve, reject) => {
        execFile(
          rt.bin,
          ["config", ...args],
          { timeout: 30000, windowsHide: true },
          (err, stdout, stderr) => {
            if (err) reject(new Error((stderr || stdout || err.message).trim()));
            else resolve({ stdout, stderr });
          },
        );
      }),
  );
}

/** Full curated schema: resolved values + enum options from the omp CLI. */
export async function getOmpConfig(): Promise<OmpConfigSection[]> {
  const [jsonOut, listOut] = await Promise.all([runConfig(["list", "--json"]), runConfig(["list"])]);
  const schema = JSON.parse(jsonOut.stdout.replace(/^\uFEFF/, "").trim()) as Record<string, SchemaEntry>;

  // `omp config list` prints enum keys as `key = value (opt1|opt2|…)`; the JSON
  // schema omits the choices, so recover them from the human output.
  const enumOptions = new Map<string, string[]>();
  for (const line of listOut.stdout.split("\n")) {
    const m = line.match(/^\s*([\w.]+)\s*=\s*\S.*\(([^()]*)\)\s*$/);
    if (m && m[2].includes("|")) {
      enumOptions.set(m[1], m[2].split("|").map((s) => s.trim()).filter(Boolean));
    }
  }

  const sections: OmpConfigSection[] = [];
  for (const group of CONFIG_GROUPS) {
    const entries: OmpConfigEntry[] = [];
    for (const key of group.keys) {
      const s = schema[key];
      if (!s) continue; // key unknown to this omp version → hide
      entries.push({
        key,
        type: s.type,
        value: s.value,
        description: s.description || "",
        options: s.type === "enum" ? enumOptions.get(key) : undefined,
      });
    }
    if (entries.length > 0) sections.push({ id: group.id, entries });
  }
  return sections;
}

function serializeValue(value: unknown, type: string): string {
  if (value === undefined || value === null) return "";
  if (type === "array" || type === "record") return JSON.stringify(value);
  if (typeof value === "boolean") return value ? "true" : "false";
  return String(value);
}

export async function setOmpConfigKey(key: string, value: unknown, type: string): Promise<void> {
  await runConfig(["set", key, serializeValue(value, type)]);
}

export async function resetOmpConfigKey(key: string): Promise<void> {
  await runConfig(["reset", key]);
}
